services:

  sql-db:
    image: postgres:15.2
    container_name: travel
    restart: always
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - POSTGRES_DB=travel
      - POSTGRES_USER=oscar
      - POSTGRES_PASSWORD=oscar
    ports:
      - "5432:5432"

  cache:
    image: redis:6.2-alpine
    container_name: travel_cache
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning --requirepass oscar

  document-db:
    image: mongo:6.0.4
    restart: always
    container_name: travel_users
    environment:
      MONGO_INITDB_ROOT_USERNAME: oscar
      MONGO_INITDB_ROOT_PASSWORD: oscar
      MONGO_INITDB_DATABASE: app_users
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
