services:

  sql-db:
    image: postgres:15.2
    container_name: travel
    restart: always
    environment:
      - POSTGRES_DB=travel
      - POSTGRES_USER=oscar
      - POSTGRES_PASSWORD=oscar
    ports:
      - "5432:5432"