services:

  sql-db:
    image: postgres:15.2
    container_name: travel-database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=travel
      - POSTGRES_USER=oscar
      - POSTGRES_PASSWORD=oscar
    ports:
      - "5432:5432"

volumes:
  postgres-data: