apiVersion: apps/v1
kind: Deployment
metadata:
  name: tour-service
  labels:
    app: tour-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tour-service
  template:
    metadata:
      labels:
        app: tour-service
    spec:
      containers:
        - name: tour-service
          image: tour-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: testdata
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://travel-postgres:5432/travel

---

apiVersion: v1
kind: Service
metadata:
  name: tour-service
  labels:
    app: tour-service
spec:
  type: ClusterIP
  selector:
    app: tour-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081