name: Commit Stage
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build, unit tests and integration tests
        working-directory: travel-backend
        run: |
          chmod +x mvnw
          ./mvnw test