name: Commit Stage
on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: omsprog/travel-backend
  VERSION: latest

jobs:
  build:
    name: Build, Test and Publish
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write
      security-events: write
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Start Docker Compose
        working-directory: travel-backend/dashboard-service
        run: docker compose up -d

      - name: Build, unit tests and integration tests
        working-directory: travel-backend/dashboard-service
        run: |
          chmod +x mvnw
          ./mvnw clean package

      - name: Stop and Clean Up Docker Compose
        if: always()
        working-directory: travel-backend/dashboard-service
        run: docker compose down

      - name: Log in to GitHub Container Registry
        if: false
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        if: false
        uses: docker/build-push-action@v5
        with:
          context: travel-backend
          file: travel-backend/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          push: true